Allow HHJ in 3D
FInAT/FInAT pull request #142
Opened 2024-10-23 16:14 UTC by pbrubeck

2024-10-29 04:16 UTC, rckirby approved these changes

2024-11-19 14:48 UTC, rckirby requested changes
Minor change (if any)

2024-11-19 16:52 UTC, pbrubeck commented on test/test_zany_mapping.py
> +    2: [
This test assumes that 3D elements are also available in 3D

2024-11-19 17:10 UTC, rckirby approved these changes

2024-11-19 18:12 UTC, rckirby approved these changes

2024-11-19 18:12 UTC, merged