AWconditioning
FInAT/FInAT pull request #88
Opened 2021-06-07 20:56 UTC by FAznaran

Small changes to the FInAT file for the Arnold--Winther elements, to make the transformation of the internal DOFs consistent with the zany theory, and to post-hoc rescale the DOFs so as to give the mass matrices O(1) conditioning.

2021-06-07 21:27 UTC, rckirby reviewed
I marked a couple of obvious flake things, and you should fix the rest of the ones that are failing.

2021-06-07 21:27 UTC, rckirby commented on finat/aw.py
> +#from gem import Literal, ListTensor
Remove the commmented line

2021-06-07 21:27 UTC, rckirby commented on finat/aw.py
> +
flake (white space)

2021-06-07 21:27 UTC, rckirby commented on finat/aw.py
>      J_np = numpy.array([[J[0, 0], J[0, 1]],
Is there syntactic sugar in gem to make this cleaner (so you don't have to explicitly index/wrap)?

2021-06-07 21:28 UTC, rckirby requested changes
Also, do we want to include a test confirming an O(1) condition number?

2021-08-19 10:00 UTC, wence- commented
@FAznaran is it possible to add a test of the conditioning? I suppose the idea is that the mass matrix should have O(1) conditioning on the reference cell? I think one can write a finat-only test to build the mass matrix and then get numeric values out using the gem evaluator.

2021-10-06 16:22 UTC, FAznaran commented
What does @pefarrell think? He's said before that if a test depends on Firedrake, it should live there. IIUC [my PR](https://github.com/firedrakeproject/firedrake/pull/2241) is currently failing its own test, I think simply since _this_ PR is not merged, which is an argument for making the test finat-only.

2021-10-06 17:12 UTC, rckirby commented
The test I am suggesting could be done entirely in FInAT (+FIAT+numpy)
without loading any Firedrake meshes, solvers, etc.  But they have the
distinct disadvantage of not existing yet.
The Firedrake PR with Firedrake-level tests couldn't be put in as a FInAT
test and would need to stay in Firedrake.

On Wed, Oct 6, 2021 at 11:22 AM FAznaran ***@***.***> wrote:

> What does @pefarrell <https://github.com/pefarrell> think? He's said
> before that if a test depends on Firedrake, it should live there. IIUC my
> PR <https://github.com/firedrakeproject/firedrake/pull/2241> is currently
> failing its own test, I think simply since *this* PR is not merged, which
> is an argument for making the test finat-only.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/FInAT/FInAT/pull/88#issuecomment-936604488>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA4XUL3U3QUUVPRNMK7PW33UFRZUZANCNFSM46IOVUSQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-07 15:18 UTC, pefarrell commented
My opinion is if the (i) FInAT-only test doesn't yet exist and (ii) it's quick to run in the firedrake test suite, then we should just keep things as-is with these PRs.

2021-10-07 16:01 UTC, merged